In [7]:
import sklearn

In [8]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,3,0])
print('A+B=',np.add(A,B))
print('A-B=',np.subtract(A,B))

A+B= [5 5 3]
A-B= [-3 -1  3]


In [12]:
C = np.array([[1,2,3],
            [1,1,1]])
D = np.array([[4,3,9,9],
            [1,1,2,2],
            [4,2,1,1]])
print(np.dot(C,D))    #dot()返回的是两个数组的点积(dot product)
print(np.matmul(C,D))     #等价于 C@D  矩阵乘积

[[18 11 16 16]
 [ 9  6 12 12]]
[[18 11 16 16]
 [ 9  6 12 12]]


 np.dot和np.matmul的区别
   都是矩阵乘法
   * np.matmul中，禁止矩阵与标量的乘法
   * np.matmul中，在矢量乘矢量的内积运算中，matmul和dot没有区别
   * np.matmul中，多维的矩阵，将前n-2维视为后2维的元素后，进行乘法操作
   
   
   
矢量内积无区别，结果都是标量

In [13]:
t1 = np.array([1,2,3])
t2 = np.array([1,2,3])
print(np.dot(t1,t2))
print(np.matmul(t1,t2))
print(t1*t2)   #元素乘积

14
14
[1 4 9]


1维与2维矩阵的乘法

In [22]:
a = np.array([1,2,3])
b = np.array([[1,1,1],
            [2,2,2],
            [3,3,3]])

np.dot(a,b)

np.matmul(a,b)

#元素乘积
a*b

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

多矩阵乘积

# 6. Markdown的基本技巧

[链接在这里哟](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

[小抄](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf)
# 一级标题
## 二级标题
**黑体**
*斜体*
>引用一段话


1. 带序号
1. 需要空格
1. 序号显示与你输入的不相关
    * 子观点

Latex

插入数学符号

$e^{i\pi}+1 = 0$

$ \sum_{\forall i}{x_i^{2}} $

\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}

\begin{equation*}
\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
\end{equation*}


[更多小抄](https://reu.dimacs.rutgers.edu/Symbols.pdf)

[更多小抄2](http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Typesetting%20Equations.html)

插入图片



![ssadsadsa](https://cdn.cubegoal.com/app_static/images/championship/upload/ddf819e8f3dd513fb5d837a7444d5e598cbfc88e.gif)

* **插入表格**

| 第一栏        | 第二栏          | 第三栏  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | 1600 |
| col 2 is      | centered      |   12 |
| zebra stripes | are neat      |    1 |